### ISSUE TITLE
Cannot find module '@fastify/awilix/classic'

### ISSUE THREAD

**Issue by tjapa** [fastify/fastify-awilix#122]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.2

### Plugin version

3.2.0

### Node.js version

v20.10.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

6.6.6-arch1-1

### Description

I getting the following error when a try to use the classic injection mode:

```Error: Cannot find module '@fastify/awilix/classic'```

### Steps to Reproduce

The code in my case is simple: 

```ts
import {
  fastifyAwilixPlugin,
  FastifyAwilixOptions,
  diContainer,
} from '@fastify/awilix/classic'
import { Lifetime, asClass, asValue } from 'awilix'
import fp from 'fastify-plugin'
import { drizzleClient } from './drizzle'
import openAi from './open-ai'

export interface AwilixPluginOptions extends FastifyAwilixOptions { }

export default fp<AwilixPluginOptions>(
  async (fastify, opts) => {
    await fastify.register(fastifyAwilixPlugin)
  },
  {
    dependencies: ['application-config', 'drizzle-plugin', 'openai-plugin'],
    name: 'awilix-plugin',
  },
)

declare module 'fastify' { }
```

**Comment by climba03003** [comment]
The document is wrong, it should be `@fastify/awilix/lib/classic`
