### ISSUE TITLE
Configure injection mode

### ISSUE THREAD

**Issue by jm42** [fastify/fastify-awilix#29]
## 🚀 Allow change Awilix injection mode

When using Awilix with Typescript, CLASSIC injection mode seems to be more desirable.

## Motivation

Awilix creator @jeffijoe [comment](https://github.com/jeffijoe/awilix/issues/89#issuecomment-386412693):

> I used to prefer the options object (which was the reason I created Awilix using Proxies to begin with), however the problem with incorrect parameter passing goes away with TypeScript, and so I've started preferring the classic approach personally. Doesn't hurt that it's faster, too, hehe.

## Example

```typescript
fastify.register(fastifyAwilixPlugin, {
  injectionMode: 'CLASSIC' // InjectionMode.CLASSIC
})
```

**Comment by kibertoad** [comment]
Released in 1.2.0
