### ISSUE TITLE
Is it possible to release a new tag?

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [fastify/fastify-awilix#83]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Is it possible to release a new tag?
With the bump of `fastify-plugin` I think it could be useful to release the new tag with it.

Thanks.

**Comment by kibertoad** [comment]
will release today, thank you for the ping

**Comment by AlessandroMinoccheri** [comment]
Thanks @kibertoad

**Comment by kibertoad** [comment]
Released as 3.0.1
